### ISSUE TITLE
Local vs. global text direction?

### ISSUE THREAD

**Issue by psyguy** [esm7/obsidian-rtl#11]
Hi again,

I do not know how easy it is to implement, but would be great if text direction could be toggled per block.

For instance, when you have an English paragraph in the middle of a Persian text, the whole note but the English paragraph would be RTL.

Thank you.

**Comment by esm7** [comment]
I'd love to see this happening, but that's not something I can do as part of this plugin because CodeMirror (the underlying text component of Obsidian) only supports a direction per document.
However, to my best understanding, the next major version -- [CodeMirror 6](https://codemirror.net/6/) -- implements BIDI much more thoroughly and supports a direction per paragraph! Hopefully it's no more than a few months away.
