### ISSUE TITLE
Cursor going to the next line (downward) when going left

### ISSUE THREAD

**Issue by mhaj98** [esm7/obsidian-rtl#4]
Thanks for the plugin.

The curser was going to the next line (downward) when moving to the left at the beginning of the first line of the paragraph.

**Comment by esm7** [comment]
@mhaj98 I don't understand the issue you are describing.
First and foremost, what's the plugin version you are using (0.0.1 or 0.0.2), and under what OS?
Next, what do you have written in the line you are describing?
Note that lines that start/end with numbers are treated differently.
Either way, unless this is the same issue fixed in 0.0.2 of the visual movement under Windows, this is probably a CodeMirror RTL behavior that is beyond the scope of this plugin. Please check if the same thing, with the same text, happens in the CodeMirror [BIDI demo](https://codemirror.net/demo/bidi.html).

**Comment by esm7** [comment]
I suspect this is the same issue as https://github.com/esm7/obsidian-rtl/issues/3 which was fixed some time ago. Closing unless more details come up.
