### ISSUE TITLE
embed icon thingy

### ISSUE THREAD

**Issue by yonatankremer** [esm7/obsidian-rtl#81]
<img width="799" alt="Screenshot 2024-04-30 at 12 16 51 PM" src="https://github.com/esm7/obsidian-rtl/assets/133390605/1c51b288-0ca2-42aa-ac16-f90d4db9e92d">
rtl makes it overlap. I don't mind turning off that option to click it, but it doesn't seem to be available. Sorry for all the issues, you're a lifesaver lol

**Comment by esm7** [comment]
The Obsidian team is working on much better native RTL support for version 1.6.0, which will make the RTL plugin much smaller in its scale (it will just add some missing functionality in the edges). Therefore I won't continue to work on plugin functionality that will become native soon, and as of the latest alpha that I'm helping the Obsidian team to test, this issue seems to not occur there :)
