### ISSUE TITLE
Broken on Version v1.6.3?

### ISSUE THREAD

**Issue by tomerganz** [esm7/obsidian-rtl#83]
Hi! For some reason all my files are auto aligned, no matter which setting I use. I don't remember enabling anything new besides the auto update.

Using plugin version 1.2.2

**Comment by esm7** [comment]
Indeed, Obsidian 1.6.3 introduces its own RTL support and the obsidian-rtl plugin is mostly redundant.
I was in a dilemma whether its little added value (mostly adding per-file settings) is worth its maintenance, so it makes me happy to hear one user noticed :smile:

**Comment by puple-banananana** [comment]
Hey! I was rather hoping you would continue support, as Obsidians RTL is Paragraph dependent, rather than global, as yours is... ant its causing issues for me with Callouts OBV. I am just one person but I could ask and hope...??

**Comment by OmarShawky1** [comment]
Hello @esm7 , Your plugin is unmatchable in comparison to the Obsidian built-in feature. I want to turn their feature off but I am not sure how to do so. I was so happy with your plugin and many thanks for that!

**Comment by esm7** [comment]
I don't think there's a way to turn off Obsidian's new built-in RTL support, but I think it's a great step forward, and this plugin will just complement the built-in support with some added features.
I think these should be:
- Assign notes to be LTR and RTL (not mixed) when required, like today.
- Remember this setting per file like today.
- Allow setting this via front matter like today.

Anything else I'm missing and should be in the plugin's 2.0.0 version?

**Comment by RyanQuey** [comment]
I'm mostly here since I want all my files to be LTR, whereas the new Obsidian feature makes each paragraph separate, making everything look awful in my files which have mixed languages (see [forum post here](https://forum.obsidian.md/t/disable-the-new-auto-rtl-feature/83327)).

> Anything else I'm missing and should be in the plugin's 2.0.0 version?

That being the case, I would like a per vault default if that's possible, so I don't have to go through and change all my files (unless this plugin does that already, setting files by default to LTR if not specified?).

**Comment by esm7** [comment]
> 
> That being the case, I would like a per vault default if that's possible, so I don't have to go through and change all my files (unless this plugin does that already, setting files by default to LTR if not specified?).

Good point, that's already the case now but I should keep in mind to preserve this behavior.

**Comment by izackv** [comment]
Your plugin was a crucial point in my decision to work with Obsidian.
Keeping points/bullets on the same RTL/LTR regardless of the first-word language is very important. 
Otherwise, it is a real mess when points start to jump from side to side.
Also, having some notes as RTL and some as LTR is essential.

**Comment by esm7** [comment]
I'll work on it this week, hopefully it goes smoothly. I verified ahead of time with the Obsidian devs that the plugin will be able to override the default behavior but haven't got a chance to try yet.

**Comment by Bacham** [comment]
I agree with all previous comments, in many cases it become a real mess when you can't decide the text direction by yourself. The ideal solution is to provide the ability to manually specify the direction of each paragraph like in Word.

**Comment by esm7** [comment]
Hi all, I did the changes required to support Obsidian 1.6.x, but since it's a very big overhaul to the code, it would be great if some of you could test it. I probably overlooked a few edge cases or more.

I created a branch with the new version here: https://github.com/esm7/obsidian-rtl/tree/v2.0
A build is attached as a zip file -- to try it, extract the 3 files to your VAULT_PATH/.obsidian/plugins/obsidian-rtl folder (best to back up the old plugin just in case).

@zoli -- as the biggest contributor to the code base, I'd love to get your impression on the updated code. I simplified it a whole lot, as detection by line is no longer necessary etc -- hope you'll be ok with many of the great things you did being no longer needed :black_heart: 

Help appreciated :pray: 

[rtl.zip](https://github.com/user-attachments/files/15990356/rtl.zip)

**Comment by Bacham** [comment]
Thank you very much! I've tested it and as long as I can see it working well.

**Comment by Bacham** [comment]
Here's a related bug report I've submitted:
https://forum.obsidian.md/t/unicode-ltr-and-rtl-character-marks-do-not-work/84276

My idea is that resolving the above issue will let the user decide the text direction of each line by simply inserting the LTR or RTL marks in the selected lines or all lines in the chosen note.
I think this is a simpler, more effective approach and more stable because less maintenance required after future Obsidian updates.

**Comment by RyanQuey** [comment]
Plugin is working great for me, no issues seen so far

**Comment by esm7** [comment]
Version 2.0.0 is now formally released, thanks everyone!

**Comment by brahem-ayad** [comment]
There is a problem, when pressing the home button on the keyboard which should take you to the start of the line, the curser is instead placed after the first character, and not before it.
