### ISSUE TITLE
how to apply rtl to code blocks ?

### ISSUE THREAD

**Issue by noor-tg** [esm7/obsidian-rtl#86]
for example I write [cucumber](https://cucumber.io/docs/gherkin/languages/) in one of the rtl locales. but even with this plugin the code block is shown from ltr.

**Comment by esm7** [comment]
It's not due to the Obsidian RTL plugin, there is an internal Obsidian CSS rule that looks like this:
```
.cm-s-obsidian .HyperMD-codeblock {
    font-family: var(--font-monospace);
    font-size: var(--code-size);
    direction: ltr;
}
```
Meaning code blocks are forced to LTR.
You can define a custom CSS snippet that would use `direction: auto` instead, but it would apply to all code blocks, not just Cucumber, which is probably a somewhat rare case of a language where it sometimes make sense to do RTL in a code block.
If you want a CSS snippet that would only apply to Cucumber, that would be more complicated, because Obsidian doesn't provide the language as a class.

**Comment by noor-tg** [comment]
Ok . thanks @esm7
